version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: db1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:9200"]
      interval: 20s
      timeout: 50s
      retries: 5
    networks:
      - my-network
    volumes:
      - es_data:/usr/share/elasticsearch/data

  backend:
    image: itsme15/ems-backend  #backend-image1
    container_name: BackendContainer #localhost1
    ports:
      - "8080:8080"
    environment:
      - ELASTICSEARCH_HOST=db1
      - ELASTICSEARCH_PORT=9200
#      - "SPRING_DATA_ELASTICSEARCH_URIS=http://host.docker.internal:9200"

    networks:
      - my-network
    depends_on:
      elasticsearch:
        condition: service_healthy


  frontend:
    image: itsme15/ems-frontend    #frontend-app1   #FRONTEND-APP1
    container_name: frontendContainer #angular-app  #ANGULAR-APP
    ports:
      - "4200:4200"
    networks:
      - my-network
    depends_on:
      - backend

networks:
  my-network:
    driver: bridge

volumes:
  es_data: