name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'v20.11.0'


    # - name: Pull Elasticsearch Image
      
    #   run: |
    #     docker pull docker.elastic.co/elasticsearch/elasticsearch:8.8.1

    - name: Create Frontend Image
      run: |
        cd FrontEnd
        cd web
        docker build -t frontend-app1:latest .

  


    # - name: Build EMSApplication with Maven
    #   run: |
    #     cd BackEnd
    #     cd EMS
    #     mvn clean package

    # - name: Create Backend Image
    #   run: |
    #     cd BackEnd
    #     cd EMS
    #     docker build -t backend-image1:latest .

 
    # - name: Set up Docker Compose
    #   run: |
    #     choco install docker-desktop
    #     choco install docker-compose
    #     docker-compose -f docker-compose.yml pull
    #     docker-compose -f docker-compose.yml build

    # - name: Push Elasticsearch Image to Docker Hub
    #   run: |
    #     docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    #     docker push docker.elastic.co/elasticsearch/elasticsearch:8.8.1

    # - name: Push Backend Image to Docker Hub
    #   run: |
    #     docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    #     docker push backend-image1

    - name: Push Frontend Image to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    #     docker push frontend-app1

    # - name: Deploying Stage
    #   run: docker-compose -f docker-compose.yml up -d
