name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check Docker daemon status
      run: docker info

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'v20.11.0'

    - name: Pull Elasticsearch Docker image
      run: docker pull docker.elastic.co/elasticsearch/elasticsearch:8.8.1

    - name: Run Elasticsearch container
      run: docker run -d --name elasticsearch -p 9200:9200 docker.elastic.co/elasticsearch/elasticsearch:8.8.1

    - name: Wait for Elasticsearch to start
      run: sleep 30 # Adjust wait time as needed

    - name: Set up Backend
      run: |
        cd BackEnd
        cd EMS
        export ELASTICSEARCH_HOST=localhost
        export ELASTICSEARCH_PORT=9200
        mvn --batch-mode --update-snapshots verify

    - name: Create Backend Image
      run: |
        cd BackEnd
        cd EMS
        docker build -t itsme15/ems-backend:latest .
    - name: Push Backend Image to Docker Hub
      run: |
        docker push itsme15/ems-backend:latest

    - name: Set up Frontend
      run: |
        cd FrontEnd
        cd web
        # You can add frontend build commands here

    - name: Create Frontend Image
      run: |
        cd FrontEnd
        cd web
        docker build -t itsme15/ems-frontend:latest .
    - name: Push Frontend Image to Docker Hub
      run: |
        docker push itsme15/ems-frontend:latest
