name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check Docker daemon status
      run: docker info

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'v20.11.0'

    - name: Pull Elasticsearch Docker image
      run: docker pull docker.elastic.co/elasticsearch/elasticsearch:8.8.1

    - name: Run Elasticsearch container
      run: docker run -d --name elasticsearch -p 9200:9200 docker.elastic.co/elasticsearch/elasticsearch:8.8.1

    - name: Check Elasticsearch container status
      run: docker ps -a

    - name: Wait for Elasticsearch to start
      run: sleep 50 # Adjust wait time as needed

    - name: Check if Elasticsearch container is in the same network
      run: docker inspect -f '{{.HostConfig.NetworkMode}}' elasticsearch
      continue-on-error: true  # Continue with the workflow even if the check fails

    - name: Check Elasticsearch health
      run: |
        for i in {1..5}; do
          curl -s -f http://localhost:9200 && break
          sleep 20
        done

    - name: Show Elasticsearch status
      run: docker ps -a

    - name: Setting up Java Maven
      uses: actions/setup-java@v4
      with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

    - name: Build Backend with Maven
      run: |
        cd BackEnd
        cd EMS
        mvn --batch-mode --update-snapshots verify

    - name: Create Backend Image
      run: |
        cd BackEnd
        cd EMS
        docker build -t itsme15/ems-backend:latest .
    - name: Push Backend Image to Docker Hub
      run: |
        docker push itsme15/ems-backend:latest

    - name: Show Backend image
      run: docker images

    - name: Create Frontend Image
      run: |
        cd FrontEnd
        cd web
        docker build -t itsme15/ems-frontend:latest .
    - name: Push Frontend Image to Docker Hub
      run: |
        docker push itsme15/ems-frontend:latest
    - name: Show Frontend image
      run: docker images
